fix: handle flaky node tracer installation (#118)
* remove return statement on node tracer installation

* use npm instead of yarn for node tracer installation

* add DD_NODE_TRACER_SKIP_INSTALL to optionally skip node tracer installation

* use node tracer installed with application if available

* remove node version command that is no longer needed

* update node debug statements for clarity

* initialize npm package before installing node tracer

diff --git a/datadog_wrapper b/datadog_wrapper
--- a/datadog_wrapper
+++ b/datadog_wrapper
@@ -152,24 +152,39 @@ startBinaries() {
 }
 
 setUpNodeEnv() {
-    NODE_RUNTIME_VERSION=$(node --version)
-    echo "Found runtime version ${NODE_RUNTIME_VERSION}"
     echo "Setting up Datadog tracing for Node"
-    echo "Installing Node tracer"
 
-    local DD_NODE_TRACER_VERSION_5=5.48.1
-
-    if [ -z "${DD_NODE_TRACER_VERSION}" ]; then
-        yarn add "dd-trace@$DD_NODE_TRACER_VERSION_5" || return
+    if [ "${DD_NODE_TRACER_SKIP_INSTALL}" = "true" ]; then
+        echo "DD_NODE_TRACER_SKIP_INSTALL set to true, skipping Datadog Node tracer installation"
     else
-        yarn add "dd-trace@$DD_NODE_TRACER_VERSION"
+        local DD_DEFAULT_NODE_TRACER_VERSION_5=5.48.1
+
+        # use provided tracer version in DD_NODE_TRACER_VERSION if available, otherwise use the default version
+        local DD_NODE_TRACER_VERSION_TO_INSTALL="${DD_NODE_TRACER_VERSION:-$DD_DEFAULT_NODE_TRACER_VERSION_5}"
+
+        # create package.json if it does not already exist, otherwise the npm install command will fail
+        echo "Initializing npm package"
+        npm init -y
+
+        echo "Installing Datadog Node tracer ${DD_NODE_TRACER_VERSION_TO_INSTALL}"
+        npm install dd-trace@${DD_NODE_TRACER_VERSION_TO_INSTALL}
     fi
 
-    ORIG_NODE_OPTIONS=$NODE_OPTIONS
-    export NODE_OPTIONS="--require=${DD_DIR}/node_modules/dd-trace/init ${ORIG_NODE_OPTIONS}"
+    ORIG_NODE_PATH=$NODE_PATH
 
-    # confirm updates to NODE_OPTIONS
-    node --help >/dev/null || (export NODE_OPTIONS="${ORIG_NODE_OPTIONS}" && return)
+    # remove trailing colon if present
+    [[ "${ORIG_NODE_PATH}" == *: ]] && MODIFIED_ORIG_NODE_PATH="${ORIG_NODE_PATH::-1}"
+
+    # use tracer installed as part of application build if available, otherwise use the tracer installed by this script
+    export NODE_PATH="${MODIFIED_ORIG_NODE_PATH}:/home/site/wwwroot/node_modules:${DD_DIR}/node_modules"
+    echo "NODE_PATH updated from '${ORIG_NODE_PATH}' to '${NODE_PATH}'"
+
+    ORIG_NODE_OPTIONS=$NODE_OPTIONS
+    export NODE_OPTIONS="--require=dd-trace/init ${ORIG_NODE_OPTIONS}"
+    echo "NODE_OPTIONS updated from '${ORIG_NODE_OPTIONS}' to '${NODE_OPTIONS}'"
+
+    # confirm updates to NODE_OPTIONS and NODE_PATH
+    node --help >/dev/null || (export NODE_OPTIONS="${ORIG_NODE_OPTIONS}" && export NODE_PATH="${ORIG_NODE_PATH}" && return)
 }
 
 setUpDotnetEnv() {
